### ISSUE TITLE
Playground v1

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/playground#1]
Playground is meant as a no-install opportunity for users to test dApps built on top of HOPR. That means users should be able to access a particular dApp and HOPR nodes through a website and not have to install software themselves.

# User Stories

- User goes to landing page (playground.hoprnet.org) and sees
  - number of total testing slots
  - number of free testing slots
  - Button to allocate a testing slot
    - if all slots are taken, an explanation is shown
- When a user allocates a testing slot
  - the cluster is allocated internally
  - and the user is provided all relevant links and guiding info on how to use and test the dApp (Myne Chat)

Wireframes and UI design: https://www.figma.com/file/LJvTvFihVBa5ZauRFBrQg5/HOPRverse---Wireframe-v1

# Components

## website
  
- this is the user-facing frontend which presents information to the user
- communicates to the backend

## backend

- coordinates clusters
  - creates/deletes/refreshes clusters
  - keeps track of allocations
- allows allocation through web-socket API
- provides cluster status information web-socket API
- each website visitor has a standing web-socket connection to the backend
- if the connection is closed, any allocated cluster is recycled

## cluster executor

- single Docker container
- starts hardhat network
- starts 5 HOPR nodes
- creates full channel topology
- ensures nodes have good quality connections to each other
- runs in Kubernetes as a single-pod deployment

## cluster orchestrator

- provides reverse proxy configuration for each cluster
- ensures connections are secured via HTTPS
- runs in Kubernetes as an ingress+cert-manager configuration
# Limitations / Requirements

- user should get access to slot within 30 seconds (if available)
- scaling of infrastructure doesn't need to be fully automated, but manually extendable
- UI is in English only

# Status (as of 11.08.2022)

- [x] backend (gravity) base structure implemented
- [x] UI implemented
- [ ] cluster simulation mode in gravity implemented
- [ ] k8s integration in gravity implemented 
  - [x] works with minikube locally
- [x] Cluster docker image available (released as hopr-pluto)
- [x] Kubernetes set up
- [ ] Helm chart for gravity 
- [ ] gravity deployed to k8s
- [x] DNS configured
  - [x] website
    - https://playground.hoprnet.org/
  - [x] backend
  - [x] clusters 
- [x] HTTPS configured
  - [x] website
  - [x] backend
- [x] https://github.com/hoprnet/hoprnet/pull/3838

# Definition of Done

- [x] components are deployed and reachable through playground.hoprnet.org
- [x] repo is documented
- [x] user can follow user stories successfully

**Comment by SCBuergel** [comment]
As allocating these clusters is resource intensive I suggest to protect that action with a captcha

**Comment by ReinhardSchmidt** [comment]
@tolbrino Approved and finished UI-Dummy: 
https://www.figma.com/file/LJvTvFihVBa5ZauRFBrQg5/HOPRverse---Wireframe-v1?node-id=0%3A1

**Comment by tolbrino** [comment]
Currently blocked by `hoprnet` CI build failures.

**Comment by tolbrino** [comment]
Main components are done. Not blocked anymore by CI. Now integration of components is outstanding.

**Comment by tolbrino** [comment]
dapps bugs: https://github.com/hoprnet/playground/issues/12

**Comment by tolbrino** [comment]
The remaining dapp bugs are handled in #12
