### ISSUE TITLE
DApp support tracker for playground v1

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/playground#12]
# Status Board

https://hopr-status-board.vercel.app/

- [x] does not support `https` endpoints, always uses `http` instead
- [ ] cannot reach other nodes because automatic ip/port calculation is not compatible with playground

# Visual

https://hopr-visual.vercel.app/

- [ ] cannot reach other nodes because automatic ip/port calculation is not compatible with playground
  - as a result no graph is shown
  - see https://github.com/hoprnet/hopr-community/blob/main/projects/hopr-visual/src/utils/dataset-utils.ts#L268

# Chess

https://hopr-chess.vercel.app/

- [x] does not follow dapp standard correctly, token isn't read from URL query parameters
  - see https://github.com/hoprnet/hopr-community/pull/160/files#diff-a25c5936bd388b3db9ea10472017a0695b4131a8af411052847d2c252272be30R192

# Boomerang Chat

https://hopr-boomerang-chat.vercel.app/

works

# Myne Chat

https://app.myne.chat/

- [x] The live version is not compatible to the dapp standard.
  - The dev version at https://int-dev-app.myne.chat/ would be though. However, it has a bug where it uses ws instead of wss even though the API uses https. Similar to the status board problem.
  - Open PR: https://github.com/hoprnet/myne-chat/pull/145

**Comment by nionis** [comment]
Closing this issue as it's no longer relevant.
